# Generated by Django 4.0.1 on 2022-03-13 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_folder', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SampleDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample1', models.IntegerField(blank=True, null=True, verbose_name='sample1')),
                ('sample2', models.CharField(blank=True, max_length=255, null=True, verbose_name='sample2')),
            ],
            options={
                'verbose_name_plural': 'sample_table',
                'db_table': 'sample_table',
            },
        ),
        migrations.AlterModelOptions(
            name='userdb',
            options={'verbose_name': 'User', 'verbose_name_plural': 'User'},
        ),
        migrations.AlterField(
            model_name='userdb',
            name='email',
            field=models.EmailField(default=3.9, max_length=254, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userdb',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
